// Code generated by protoc-gen-go.
// source: models.proto
// DO NOT EDIT!

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	models.proto

It has these top-level messages:
	EncryptReq
	EncryptRes
	DecryptReq
	DecryptRes
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptReq struct {
	Id               []byte `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Data             []byte `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EncryptReq) Reset()                    { *m = EncryptReq{} }
func (m *EncryptReq) String() string            { return proto.CompactTextString(m) }
func (*EncryptReq) ProtoMessage()               {}
func (*EncryptReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EncryptReq) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *EncryptReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EncryptRes struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *EncryptRes) Reset()                    { *m = EncryptRes{} }
func (m *EncryptRes) String() string            { return proto.CompactTextString(m) }
func (*EncryptRes) ProtoMessage()               {}
func (*EncryptRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EncryptRes) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DecryptReq struct {
	Id               []byte `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Key              []byte `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DecryptReq) Reset()                    { *m = DecryptReq{} }
func (m *DecryptReq) String() string            { return proto.CompactTextString(m) }
func (*DecryptReq) ProtoMessage()               {}
func (*DecryptReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DecryptReq) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DecryptReq) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DecryptRes struct {
	Data             []byte `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DecryptRes) Reset()                    { *m = DecryptRes{} }
func (m *DecryptRes) String() string            { return proto.CompactTextString(m) }
func (*DecryptRes) ProtoMessage()               {}
func (*DecryptRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DecryptRes) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptReq)(nil), "EncryptReq")
	proto.RegisterType((*EncryptRes)(nil), "EncryptRes")
	proto.RegisterType((*DecryptReq)(nil), "DecryptReq")
	proto.RegisterType((*DecryptRes)(nil), "DecryptRes")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0x4f, 0x49,
	0xcd, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe3, 0xe2, 0x72, 0xcd, 0x4b, 0x2e,
	0xaa, 0x2c, 0x28, 0x09, 0x4a, 0x2d, 0x14, 0xe2, 0xe2, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd2, 0xe0, 0x11, 0xe2, 0xe1, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x02, 0xf1, 0x94, 0x24,
	0x91, 0xd4, 0x15, 0x0b, 0x71, 0x73, 0x31, 0x67, 0xa7, 0x56, 0x42, 0x14, 0x2a, 0xa9, 0x72, 0x71,
	0xb9, 0xa4, 0x62, 0x35, 0x02, 0xaa, 0x0c, 0x62, 0x82, 0x14, 0x92, 0xb2, 0x62, 0xb8, 0xe9, 0x60,
	0x85, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x39, 0x11, 0x12, 0x94, 0x00, 0x00, 0x00,
}
